platform :ios, ‘8.0’
target 'MMJH_YXPT' do
pod 'AFNetworking','~> 2.0'
pod 'JSONKit', '~> 1.5pre'
pod 'MJRefresh', '~> 3.0.7'
pod 'SDWebImage', '~> 3.7.3'
pod 'Masonry', '~> 0.6.2'
pod 'SVProgressHUD', '~> 2.0-beta'
pod 'MJExtension', '~> 2.5.3'
pod 'ReactiveCocoa', '~> 2.5'
pod 'RDVTabBarController', '~> 1.1.9'
pod 'YYKit'
pod 'IQKeyboardManager'
pod 'BaiduMapKit' #百度地图SDK
end
